config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'articles#index'

  get 'password_resets/new'
  get 'password_resets/edit'

  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'

  resources :articles
  resources :wx_users do
    get :wx_login, on: :collection
  end

  resources :users
  resources :password_resets,      only: [:new, :create, :edit, :update]




  resources :web_sites, only: [] do
    collection do
      get :rose, :fireworks, :heart
    end
  end

  namespace :back do
    resources :articles
    resources :accounts

  end

  namespace :mobile do
    resources :users
    resources :articles
    resources :flows
    resources :settlements
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_secure_password
  
end

app/controllers/back/accounts_controller.rb
class Back::AccountsController < Back::BaseController
	
  def index
    @query = Account.ransack(params[:q])
    @accounts = @query.result.page(params[:page]).per(10)
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  private

    def find_account
      @account = Account.find(params[:id].to_i) rescue nil
      return redirect_to :back || back_accounts_path, alert: "账号信息不存在 请查证后再试" unless @account
    end  
end

app/controllers/back/articles_controller.rb
class Back::ArticlesController < Back::BaseController
  before_filter :set_article, only: [:show,:destroy]
	
  def index
  	@query = Article.ransack(params[:q])
    @articles = @query.result.page(params[:page])
    respond_to :html, :json
  end

  def new
  	@article = Article.new
  end

  def create
  	@article = Article.new(article_params)
  	if @article.save
  	  redirect_to back_articles_path
  	else
  	  render :edit
  	end
  end

  def show
    respond_to :html, :json
  end

  def destroy
    @article.destroy
    redirect_to :back
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit!
    end
end

app/controllers/back/base_controller.rb
# -*- encoding : utf-8 -*-

class Back::BaseController < ApplicationController
  layout "back"

  # 用户登录后24小时内不做任何操作将自动退出
  # MAX_SESSION_TIME = 60 * 60 * 24

  # ADMIN_FILTERS = [:required_sign_in]

  # before_filter :prepare_session, :set_current_user
  # before_filter *ADMIN_FILTERS
  # helper_method :current_user

  # private

  # def prepare_session
  #   if session[:expiry_time].present? and session[:expiry_time] < Time.now
  #     reset_session
  #   end
  #   session[:expiry_time] = MAX_SESSION_TIME.seconds.from_now
  #   return true
  # end

  # def set_current_user
  #   User.current = current_user
  # end

  # def required_sign_in
  #   unless current_user
  #     flash[:alert] = "你还没有登录，请先登录..."
  #     store_location
  #     redirect_to wap_sign_in_path
  #   end
  # end

  # def current_user(force_reload = false)
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  #   @current_user.reload if force_reload
  #   @current_user
  # end

  # def store_location
  #   session[:return_to] = request.path
  # end

  # def clear_sign_in_session
  #   session[:user_id] = nil
  # end

end

app/controllers/back/sessions_controller.rb
class Back::SessionsController < Back::BaseController
  skip_before_filter *ADMIN_FILTERS

  def new
  end

  def create
    clear_sign_in_session

    if account = Account.authenticated(params[:mobile], params[:password])
      session[:user_id] = user.id
      return render json: {code: 0, url: , message: "登录成功!", status: 1}
    else
      return render json: {code: -2, message: "帐号或密码错误", status: 0}
    end
  rescue => error
    return render json: {code: -3, message: '登录失败', status: 0}
  end

  def destroy
    clear_sign_in_session

    redirect_to ''
  end
end

app/views/back/accounts/index.html.erb
<section id="main-content">
    <section class="wrapper">
    	<h3><i class="fa fa-angle-right"></i>用户列表</h3>
    	<div class="row">
    		<div class="col-md-12">
    		  <div class="content-panel">
            <table class="table table-striped table-advance table-hover">
              <!-- <h4><i class="fa fa-angle-right"></i>文章</h4>
              <hr> -->
              <thead>
                <tr>
                  <th><i class="fa fa-bullhorn"></i>a</th>
                  <th class="hidden-phone"><i class="fa fa-question-circle"></i> b</th>
                  <th><i class="fa fa-bookmark"></i> c</th>
                  <th><i class=" fa fa-edit"></i> d</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @accounts.each_with_index do |account, index| %>
                  <tr>
                    <td><%= show_index(index) %></td>
                    <td><%= account.nickname %></td>
                    <td><%= account.status %></td>
                    <td><%=  %></td>
                    <td><%=  %></td>
                    <td>
                      <%#= link_to article_path(article), class: 'btn btn-success btn-xs' do %>
                        <!-- <i class="fa fa-check"></i> -->
                      <%# end %>
                      <%= link_to edit_back_account_path(account), class: "btn btn-primary btn-xs" do %>
                        <i class="fa fa-pencil"></i>
                      <% end %>
                      <%= link_to back_account_path(account), method: :delete, data: { confirm: '确定删除？' }, class: "btn btn-danger btn-xs" do %>
                        <i class="fa fa-trash-o "></i>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <%= paginate @accounts %>
    		</div>
    	</div>

  </section>
</section>