config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'articles#index'

  get 'password_resets/new'
  get 'password_resets/edit'

  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'

  resources :articles
  resources :wx_users do
    get :wx_login, on: :collection
  end

  resources :users
  resources :password_resets,      only: [:new, :create, :edit, :update]




  resources :web_sites, only: [] do
    collection do
      get :rose, :fireworks, :heart
    end
  end

  namespace :back do
    resources :articles
    resources :accounts

  end

  namespace :mobile do
    resources :users
    resources :articles
    resources :flows
    resources :settlements
  end

end

app/models/flow.rb
class Flow < ActiveRecord::Base

  belongs_to :user

  enum_attr :category, in: [
    ['in',    1, '收入'],
    ['out',   2, '支出']
  ]

  enum_attr :paytype, in: [
    ['alipay',  1,  '支付宝'],
    ['wxpay',   2,  '微信'],
    ['cash',    3,  '现金'],
    ['bcard',   4,  '银行卡']
  ]
  before_create :set_index
  after_create :set_settlement

  def set_index
  	time = Time.now
  	self.index_day = Concerns::IndexTime.index_day(time)
  	self.index_month = Concerns::IndexTime.index_month(time)
  	self.index_year = Concerns::IndexTime.index_year(time)
  end

  def set_settlement
  	settlement = user.settlements.where(index_day: self.index_day).first_or_initialize
  	settlement.amount =  self.in? ? settlement.amount.to_f + self.amount.to_f : settlement.amount.to_f - self.amount.to_f
  	settlement.save
  	self.update_column(:settlement_id, settlement.id)
  end
  

end

app/controllers/mobile/articles_controller.rb
class Mobile::ArticlesController < Mobile::BaseController
	
  def index
  	@query = Article.ransack(params[:q])
    @articles = @query.result.page(params[:page])
    respond_to do |format|
    	format.html
    	format.json {render json: {errcode: true, errmsg: 'ok', data: @articles }}
    end
  end 
end

app/controllers/mobile/base_controller.rb
class Mobile::BaseController < ActionController::Base
  layout "mobile"

  # 用户登录后24小时内不做任何操作将自动退出
  # MAX_SESSION_TIME = 60 * 60 * 24

  # ADMIN_FILTERS = [:required_sign_in]
  before_filter :set_current_user
  # before_filter :prepare_session, :set_current_user
  # before_filter *ADMIN_FILTERS
  # helper_method :current_user

  # private

  def set_current_user
  	@user = User.first
  end

  # def prepare_session
  #   if session[:expiry_time].present? and session[:expiry_time] < Time.now
  #     reset_session
  #   end
  #   session[:expiry_time] = MAX_SESSION_TIME.seconds.from_now
  #   return true
  # end

  # def set_current_user
  #   User.current = current_user
  # end

  # def required_sign_in
  #   unless current_user
  #     flash[:alert] = "你还没有登录，请先登录..."
  #     store_location
  #     redirect_to wap_sign_in_path
  #   end
  # end

  # def current_user(force_reload = false)
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  #   @current_user.reload if force_reload
  #   @current_user
  # end

  # def store_location
  #   session[:return_to] = request.path
  # end

  # def clear_sign_in_session
  #   session[:user_id] = nil
  # end

end

app/controllers/mobile/flows_controller.rb
class Mobile::FlowsController < Mobile::BaseController
	
  def index
    
  end

  def new
  	@flow = @user.flows.new
  end 
end

app/controllers/mobile/users_controller.rb
class Mobile::UsersController < Mobile::BaseController
	
  def index
    @user = User.first
  end 
end

app/views/mobile/flows/_form.html.erb
<%= form_for @flow, url: @flow.new_record? ? mobile_flows_path : mobile_flow_path(@flow) do |f| %>
  <div class="dingdanlist">
    <table>
      <tr>
        <td colspan="3" style="height:10px; background:#efefef;padding:0;"></td>
      </tr>

      <tr>
        <td class="dingimg" width="60%" colspan="2">类别</td>
        <td align="right">
          <%= f.select :category, Flow.category_options, {include_blank: '请选择'}, class: "hui" %>
        </td>
      </tr>

      <tr>
        <td class="dingimg" width="60%" colspan="2">支付方式</td>
        <td align="right">
          <%= f.select :category, Flow.paytype_options, {include_blank: '请选择'}, class: "hui" %>
        </td>
      </tr>

      <tr>
        <td class="dingimg" width="60%" colspan="2">价格</td>
        <td align="right">
          <%= f.number_field :price, placeholder: "请输入价格" %>
        </td>
      </tr>

      <tr>
        <td class="dingimg" width="60%" colspan="2">数量</td>
        <td align="right">
          <%= f.number_field :qty, placeholder: "请输入数量" %>
        </td>
      </tr>

      <tr>
        <td class="dingimg" width="60%" colspan="2">总价</td>
        <td align="right">
          <%= f.number_field :amount, placeholder: "总价" ,style: " text-align: right;" %>
        </td>
      </tr>

      <tr>
        <td class="dingimg" width="60%" colspan="2">备注</td>
        <td align="right">
          <%= f.text_area :description, placeholder: "备注" %>
        </td>
      </tr>

      <tr>
        <td class="dingimg" width="15%">
          <img src="" />
        </td>
        <td width="50%">
          <h3>三级分销农庄有机瓢瓜400g</h3>
          <time>下单时间：2015-08-11  13:51</time>
        </td>
        <td align="right"><span class="qingdan">X 1</span></td>
      </tr>

      <tr>
        <th colspan="3"><strong class="orange">¥36.60</strong></th>
      </tr>
     
      <tr>
        <td class="dingimg" width="75%" colspan="2">商品金额</td>
        <td align="right"><strong class="orange">¥68.80</strong></td>
      </tr>

      <tr>
        <td class="dingimg" width="75%" colspan="2">折扣优惠</td>
        <td align="right"><strong class="green">¥0.00</strong></td>
      </tr>

      <tr>
        <td class="dingimg" width="75%" colspan="2">抵扣金额</td>
        <td align="right"><strong class="green">¥0.00</strong></td>
      </tr>

      <tr>
        <td class="dingimg" width="75%" colspan="2">运费</td>
        <td align="right"><strong class="orange">¥20.80</strong></td>
      </tr>
    </table>

  </div><!--dingdanlist/-->
<% end %>

<div class="height1"></div>
<div class="gwcpiao">
  <table>
    <tr>
      <th width="10%">
        <a href="javascript:history.back(-1)">
          <span class="glyphicon glyphicon-menu-left"></span>
        </a>
      </th>
      <td width="50%">总计：<strong class="orange"></strong></td>
      <td width="40%"><a href="success.html" class="jiesuan">提交</a></td>
    </tr>
  </table>
</div>
<style type="text/css">
  input{
    border: none;
  }
</style>

app/views/mobile/flows/edit.html.erb
<%# title '修改' %>
<header>
  <a href="javascript:history.back(-1)" class="back-off fl" style="top: 10px;"><span class="glyphicon glyphicon-menu-left"></span></a>
  <div class="head-mid">
    <h1>修改</h1>
  </div>
</header>
<%= render "form" %>

app/views/mobile/flows/index.html.erb
<%# title '列表' %>

app/views/mobile/flows/new.html.erb
<%# title '新增' %>
<header>
  <a href="javascript:history.back(-1)" class="back-off fl" style="top: 10px;"><span class="glyphicon glyphicon-menu-left"></span></a>
  <div class="head-mid">
    <h1>新增</h1>
  </div>
</header>
<%= render "form" %>